# Historical Performance Lending and Borrowing in Compund Markets

In [16]:
#Libraries
import pandas as pd
import numpy as np
import scipy
import matplotlib.pyplot as plt
import requests
from datetime import datetime
from pandas.io.json import json_normalize
import pickle
import os 
import sys
from datetime import date
import math

In [17]:
pathAPI = os.getcwd()
pathData = os.path.join(pathAPI,'data')

In [18]:
#Load Downloaded Data
f = open(os.path.join(pathData,'cETH_daily.pickle'), 'rb')
cethHD = pickle.load(f)     
f.close()

In [19]:
#Load Downloaded Data
f = open(os.path.join(pathData,'cDAI_daily.pickle'), 'rb')
cdaiHD = pickle.load(f)     
f.close()

## Historical Daily Data from ETH and DAI market

In [20]:
#Retrive data ETH market
BR=json_normalize(cethHD['borrow_rates'],sep="_")
BR['rate'] = BR['rate'].astype(float)
BR.index=pd.to_datetime(BR['block_timestamp'], unit='s')
BR.index=pd.to_datetime(BR.index.date)
BR_E=BR.rate
SR=json_normalize(cethHD['supply_rates'],sep="_")
SR['rate'] = SR['rate'].astype(float)
SR.index=pd.to_datetime(SR['block_timestamp'], unit='s')
SR.index=pd.to_datetime(SR.index.date)
SR_E=SR.rate
TS=json_normalize(cethHD['total_supply_history'],sep="_")
TS['total_value'] = TS['total_value'].astype(float)
TS.index=pd.to_datetime(TS['block_timestamp'], unit='s')
TS.index=pd.to_datetime(TS.index.date)
TS_E=TS.total_value
TB=json_normalize(cethHD['total_borrows_history'],sep="_")
TB['total_value'] = TB['total_value'].astype(float)
TB.index=pd.to_datetime(TB['block_timestamp'], unit='s')
TB.index=pd.to_datetime(TB.index.date)
TB_E=TB.total_value
Xrate=json_normalize(cethHD['exchange_rates'],sep="_")
Xrate['rate'] = Xrate['rate'].astype(float)
Xrate.index=pd.to_datetime(Xrate['block_timestamp'], unit='s')
Xrate.index=pd.to_datetime(Xrate.index.date)
Xrate_E=Xrate.rate
PUSD=json_normalize(cethHD['prices_usd'],sep="_")
PUSD['price_value'] = PUSD['price_value'].astype(float)
PUSD.index=pd.to_datetime(PUSD['block_timestamp'], unit='s')
PUSD.index=pd.to_datetime(PUSD.index.date)
PUSD_E=PUSD.price_value
Uta_E=pd.Series((SR_E.values/(BR_E.values*(1-0.2))),index=BR_E.index) #Reserve Factor 20%

In [21]:
#Retrive data DAI market
BR=json_normalize(cdaiHD['borrow_rates'],sep="_")
BR['rate'] = BR['rate'].astype(float)
BR.index=pd.to_datetime(BR['block_timestamp'], unit='s')
BR.index=pd.to_datetime(BR.index.date)
BR_D=BR.rate
SR=json_normalize(cdaiHD['supply_rates'],sep="_")
SR['rate'] = SR['rate'].astype(float)
SR.index=pd.to_datetime(SR['block_timestamp'], unit='s')
SR.index=pd.to_datetime(SR.index.date)
SR_D=SR.rate
TS=json_normalize(cdaiHD['total_supply_history'],sep="_")
TS['total_value'] = TS['total_value'].astype(float)
TS.index=pd.to_datetime(TS['block_timestamp'], unit='s')
TS.index=pd.to_datetime(TS.index.date)
TS_D=TS.total_value
TB=json_normalize(cdaiHD['total_borrows_history'],sep="_")
TB['total_value'] = TB['total_value'].astype(float)
TB.index=pd.to_datetime(TB['block_timestamp'], unit='s')
TB.index=pd.to_datetime(TB.index.date)
TB_D=TB.total_value
Xrate=json_normalize(cdaiHD['exchange_rates'],sep="_")
Xrate['rate'] = Xrate['rate'].astype(float)
Xrate.index=pd.to_datetime(Xrate['block_timestamp'], unit='s')
Xrate.index=pd.to_datetime(Xrate.index.date)
Xrate_D=Xrate.rate
PUSD=json_normalize(cdaiHD['prices_usd'],sep="_")
PUSD['price_value'] = PUSD['price_value'].astype(float)
PUSD.index=pd.to_datetime(PUSD['block_timestamp'], unit='s')
PUSD.index=pd.to_datetime(PUSD.index.date)
PUSD_D=PUSD.price_value
Uta_D=pd.Series((SR_E.values/(BR_E.values*(1-0.2))),index=BR_E.index) #Reserve Factor 20%

In [ ]:
#ETH data
#frame = {'Borrow Rate': BR_E, 'Utilization Rate': Uta_E,'Supply Rate': SR_E, 'T. Borrow(Wei)': TB_E, 'T. Supply(Wei)': TS_E,  'X_rate_cToken': Xrate_E, 'Tk.Price(USD)': PUSD_E }
#D_ETH = pd.DataFrame(frame)
#D_ETH.head()
#D_ETH.to_excel('CompundH_ETH.xlsx')

In [22]:
#DAI data
#frame = {'Borrow Rate': BR_D, 'Utilization Rate': Uta_D,'Supply Rate': SR_D, 'T. Borrow(Wei)': TB_D, 'T. Supply(Wei)': TS_D,  'X_rate_cToken': Xrate_D, 'Tk.Price(USD)': PUSD_D }
#D_DAI = pd.DataFrame(frame)
#D_DAI.head()
#D_DAI.to_excel('CompundH_DAI.xlsx')

## Returns for Passive Investors - Suppliers

In [23]:
def passiveInv_ETH(USDInv,mofInv, horizon):
    #initial date index
    ip=BR_E.index.get_loc(mofInv, method='nearest')
    ia_ETH=USDInv/PUSD_E.iloc[ip]
    ia_cETH=ia_ETH/Xrate_E.iloc[ip]
    if (ip+horizon > len(BR_E.index)):
        print("Investment Horizon oversteps historical data")
    else:
        o_ETH=ia_cETH*Xrate_E.iloc[ip+horizon]
        ti_inc=(o_ETH-ia_ETH)*PUSD_E.iloc[ip+horizon]
        p_inc=PUSD_E.iloc[ip+horizon]-PUSD_E.iloc[ip]
        ti_ret=(ti_inc/(ia_ETH*PUSD_E.iloc[ip+horizon]))*100
        dp_ret= (p_inc/PUSD_E.iloc[ip])*100
    idt=(USDInv,ia_ETH,ia_cETH,math.nan,math.nan,math.nan,math.nan)
    hdt=((o_ETH*PUSD_E.iloc[ip+horizon]),o_ETH,ia_cETH,ti_inc,p_inc,ti_ret,dp_ret)
    vnames=('USD','ETH','cETH','int. Income','Price Income','int. %','Price %')
    tbl= pd.DataFrame(np.concatenate((idt,hdt)).reshape(2,7).transpose(), index=vnames,columns=["initial",'days'+str(horizon)])
    return tbl.round(4)

In [24]:
passiveInv_ETH(1000,date(2019, 12, 15), 360)

                initial    days360
USD           1000.0000  3932.5577
ETH              6.8223     6.8288
cETH           340.9327   340.9327
int. Income         NaN     3.7249
Price Income        NaN   429.3017
int. %              NaN     0.0948
Price %             NaN   292.8833

In [25]:
def passiveInv_DAI(USDInv,mofInv, horizon):
    #initial date index
    ip=BR_D.index.get_loc(mofInv, method='nearest')
    ia_ETH=USDInv/PUSD_D[ip]
    ia_cETH=ia_ETH/Xrate_D[ip]
    if (ip+horizon > len(BR_D.index)):
        print("Investment Horizon oversteps historical data")
    else:
        o_ETH=ia_cETH*Xrate_D[ip+horizon]
        ti_inc=(o_ETH-ia_ETH)*PUSD_D[ip+horizon]
        p_inc=PUSD_D[ip+horizon]-PUSD_D[ip]
        ti_ret=(ti_inc/(ia_ETH*PUSD_D[ip+horizon]))*100
        dp_ret= (p_inc/PUSD_E[ip])*100
    idt=(USDInv,ia_ETH,ia_cETH,math.nan,math.nan,math.nan,math.nan)
    hdt=((o_ETH*PUSD_D[ip+horizon]),o_ETH,ia_cETH,ti_inc,p_inc,ti_ret,dp_ret)
    vnames=('USD','DAI','cDAI','int. Income','Price Income','int. %','Price %')
    tbl= pd.DataFrame(np.concatenate((idt,hdt)).reshape(2,7).transpose(), index=vnames,columns=["initial",'days'+str(horizon)])
    return tbl.round(4)

In [26]:
passiveInv_DAI(1000,date(2019, 12, 15), 360)

                 initial     days360
USD            1000.0000   1049.0850
DAI            1003.1328   1043.6258
cDAI          50137.5039  50137.5039
int. Income          NaN     40.7048
Price Income         NaN      0.0084
int. %               NaN      4.0367
Price %              NaN      0.0050

## Borrower ETH

In [27]:
USDm=1000
dinv=date(2019, 12, 15)
horizon=90
safety=0.3

In [58]:
def borrower_ETH(USDm,dinv,horizon,safety):
    cf_E=0.75
    ip_E=BR_E.index.get_loc(dinv, method='nearest')
    #initial amount of Collateral 
    ia_ETH=USDm/PUSD_E.iloc[ip_E] #in ether
    ia_cETH=ia_ETH/Xrate_E[ip_E] #in cETH
    #Max Borrow in collateral currency: ETH
    mx_b_ETH=ia_ETH*cf_E
    #Borrow 
    b_ETH=mx_b_ETH*(1-safety) #in ETH keeps a buffer defined by safetty 
    b_USD=b_ETH*PUSD_E.iloc[ip_E] # in USD uses the money outside of protocol
    b_cETH=b_ETH/Xrate_E[ip_E] # in cETH
    Mcalls=sum(mx_b_ETH/(b_USD/PUSD_E[ip_E:ip_E+horizon])<1) #Number of Margin Calls over investment horizon
    pay_ETH=b_cETH*Xrate_E.iloc[ip_E+horizon] #accured interest in form of cETH in ETH for borrowing in ETH
    pay_USD=pay_ETH*PUSD_E.iloc[ip_E+horizon] #borrowed to pay in USD
    loan_cost=(pay_USD-b_USD) #interest payed in USD cost of loan
    ti_cost=(pay_ETH-b_ETH)*PUSD_E.iloc[ip_E+horizon]  #in USD
    p_inc=PUSD_E.iloc[ip_E+horizon]-PUSD_E.iloc[ip_E]
    # Percentages
    ti_ret_cost=(ti_cost/b_USD)*100
    dp_ret= (p_inc/PUSD_E.iloc[ip_E])*100
    idt=(USDm,   ia_ETH,ia_cETH, b_USD, b_ETH, math.nan, math.nan, math.nan, math.nan, math.nan )
    hdt=(math.nan,math.nan, math.nan,  pay_USD, pay_ETH, Mcalls, ti_cost, p_inc, ti_ret_cost, dp_ret)
    vnames=('USD','ETH','cETH','Borrow USD','Borrow ETH', 'MCalls','Int. Pay',  'Price Income','int. pay %','Price %')
    tbl= pd.DataFrame(np.concatenate((idt,hdt)).reshape(2,10).transpose(), index=vnames,columns=["initial",'days'+str(horizon)])
    return tbl.round(4)

In [62]:
borrower_ETH(1000,date(2019, 12, 15),90,0.3)

                initial    days90
USD           1000.0000       NaN
ETH              6.8223       NaN
cETH           340.9327       NaN
Borrow USD     525.0000  716.7617
Borrow ETH       3.5817    3.5818
MCalls              NaN    0.0000
Int. Pay            NaN    0.0265
Price Income        NaN   53.5316
int. pay %          NaN    0.0051
Price %             NaN   36.5210

In [60]:
borrower_ETH(1000,date(2020, 3, 15),60,0.3)

                initial    days60
USD           1000.0000       NaN
ETH              4.9655       NaN
cETH           248.1302       NaN
Borrow USD     525.0000  492.0047
Borrow ETH       2.6069    2.6069
MCalls              NaN   21.0000
Int. Pay            NaN    0.0114
Price Income        NaN  -12.6614
int. pay %          NaN    0.0022
Price %             NaN   -6.2870

## Borrowing in Compound (margin trader) post collateral in liquid crypto ETH borrow in DAI

In [56]:
def activeInv(USDm,dinv,horizon,safety):
    #collateral market parameter
    cf_E=0.75
    #investment date index
    ip_E=BR_E.index.get_loc(dinv, method='nearest')
    ip_D=BR_D.index.get_loc(dinv, method='nearest')
    #initial amount of Collateral 
    ia_ETH=USDm/PUSD_E.iloc[ip_E] #in ether
    ia_cETH=ia_ETH/Xrate_E[ip_E] #in cETH
    #Max Borrow in collateral currency: ETH
    mx_b_ETH=ia_ETH*cf_E
    #Borrow 
    b_ETH=mx_b_ETH*(1-safety) #in ETH keeps a buffer defined by safetty 
    #r_cETH=ia_cETH-(b_ETH/Xrate_E[ip_E]) # remaning cETH
    CR=((PUSD_E[ip_E]*ia_ETH)/(PUSD_E[ip_E]*b_ETH))*100 #collatreral ratio un USD min 133 
    b_USD=b_ETH*PUSD_E.iloc[ip_E] # in USD
    b_DAI=b_USD/PUSD_D.iloc[ip_D] # in DAI
    b_cDAI=b_DAI/Xrate_D.iloc[ip_D] #in cDAI
    #Use borrow to leverage ETH Portfolio
    add_ETH=b_USD/PUSD_E.iloc[ip_E] #in ETH
    l_ETH=ia_ETH+add_ETH #leveraged portfolio in ETH
    l_cETH=l_ETH/Xrate_E.iloc[ip_E] #leveraged portfolio in cETH
    x_Leverage=l_ETH/ia_ETH # x times leverage
    Mcalls=sum(mx_b_ETH/(b_USD/PUSD_E[ip_E:ip_E+horizon])<1) #Number of Margin Calls over investment horizon
    #Value at the end of investment horizon
    #o_ETH=l_cETH*Xrate_E.iloc[ip_E+horizon] #accured interest from cETH to ETH
    ti_inc=(ia_cETH*Xrate_E.iloc[ip_E+horizon]-ia_ETH)*PUSD_E.iloc[ip_E+horizon] #interest paid in USD for suppling ETH 
    pay_DAI=b_cDAI*Xrate_D.iloc[ip_D+horizon] #accured interest in form of cDAI in DAI for borrowing in DAI
    pay_USD=pay_DAI*PUSD_D.iloc[ip_D+horizon] #borrowed to pay in USD
    ti_cost=(pay_USD-b_USD) #interest payed in USD cost of loan
    benefit=l_ETH*PUSD_E.iloc[ip_E+horizon]-pay_USD #value of investment at end of horizon
    p_inc=PUSD_E.iloc[ip_E+horizon]-PUSD_E.iloc[ip_E]
    # Percentages
    ti_ret_inc=(ti_inc/(ia_ETH*PUSD_E.iloc[ip_E+horizon]))*100
    ti_ret_cost=(ti_cost/b_USD)*100
    dp_ret= (p_inc/PUSD_E.iloc[ip_E])*100
    idt=(USDm,   ia_ETH,ia_cETH, b_USD, x_Leverage, Mcalls,           math.nan, math.nan, math.nan, math.nan )
    hdt=(benefit,l_ETH, l_cETH,  pay_USD, ti_inc,        ti_cost,      p_inc,         ti_ret_inc,  ti_ret_cost, dp_ret)
    vnames=('USD','ETH','cETH','Borrow USD', 'xlev/Int. Income', 'MCalls/Int. Pay',  'Price Income','int. inc %','int. pay %','Price %')
    tbl= pd.DataFrame(np.concatenate((idt,hdt)).reshape(2,10).transpose(), index=vnames,columns=["initial",'days'+str(horizon)])
    return tbl.round(4)

In [57]:
activeInv(1000,date(2019, 12, 15),360,0.3)

                    initial    days360
USD               1000.0000  5440.7003
ETH                  6.8223    10.4040
cETH               340.9327   519.9224
Borrow USD         525.0000   550.7696
xlev/Int. Income     1.5250     3.7249
MCalls/Int. Pay      0.0000    25.7696
Price Income            NaN   429.3017
int. inc %              NaN     0.0948
int. pay %              NaN     4.9085
Price %                 NaN   292.8833